#SETTINGS
app:
  external-url: http://localhost:8080

#SPRING
spring:
  application:
    version: ${spring.application.name}-BETA

  #JPA
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

  #FLYWAY
  flyway:
    enabled: false

  #DATA SOURCE
  datasource:
    url: jdbc:postgresql://otto.db.elephantsql.com:5432/cnbwloce
    username: cnbwloce
    password: 342G6Sw0UqmlAQQkgJFR2QDJzQwD5SxC
