#SETTINGS
app:
  external-url: http://localhost:8080

#SPRING
spring:
  application:
    version: ${spring.application.name}-BETA
  
  #JPA
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
  
  #FLYWAY
  flyway:
    enabled: true
    
  #DATA SOURCE
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/${spring.application.name}
    username: cvmanager
    password: cvmanager