spring:
  application.name: cvmanager
  profiles:
    active: @active.profile@
    
  #FLYWAY
  flyway:
    check-location: true
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix: v  
      
  #JPA
  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate.default_schema: public
      hibernate.jdbc.lob.non_contextual_creation: true

  #STATIC RESOURCES
  resources.static-locations: classpath:/static/
  resources.chain:
    cache: false
    strategy.content.enabled: true
    strategy.content.paths: /**

  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/static/
    suffix: .html

  http:
    multipart:
      max-file-size: 8MB
      
upload:
  paths: 
    image: uploads/img
