#SETTINGS
app:
  external-url: http://localhost:8080

#SPRING
spring:
  application:
    version: ${spring.application.name}-RELEASE
  
  #JPA
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
    
  #FLYWAY
  flyway:
    enabled: true