SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS public;

ALTER SCHEMA public OWNER TO cvmanager;

SET default_tablespace = '';

SET default_with_oids = false;

CREATE TABLE public.personal_info (
	id bigint NOT NULL CONSTRAINT personal_info_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created timestamp without time zone NOT NULL,
	updated timestamp without time zone,
	title varchar(30) NOT NULL,
	subtitle varchar(50),
	first_name varchar(100) NOT NULL,
	last_name varchar(100),
	about_me text,
	image text
);

CREATE TABLE public.phone (
	id bigint NOT NULL CONSTRAINT phone_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created timestamp without time zone NOT NULL,
	updated timestamp without time zone,
	number varchar(30) NOT NULL,
	personal_info_id bigint NOT NULL REFERENCES public.personal_info(id)
);

CREATE TABLE public.email (
	id bigint NOT NULL CONSTRAINT email_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created timestamp without time zone NOT NULL,
	updated timestamp without time zone,
	address varchar(255) NOT NULL,
	personal_info_id bigint NOT NULL REFERENCES public.personal_info(id)
);

CREATE TABLE public.reference (
	id bigint NOT NULL CONSTRAINT reference_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created timestamp without time zone NOT NULL,
	updated timestamp without time zone,
	name varchar(100) NOT NULL,
	contact varchar(255),
	personal_info_id bigint NOT NULL REFERENCES public.personal_info(id)
);

CREATE TABLE public.graduation (
	id bigint NOT NULL CONSTRAINT graduation_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created timestamp without time zone NOT NULL,
	updated timestamp without time zone,
	course varchar(100) NOT NULL,
	institute varchar(100) NOT NULL,
	title varchar(50),
	status varchar(50),
	period varchar(10)
);

CREATE TABLE public.professional_experience (
	id bigint NOT NULL CONSTRAINT professional_experience_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created timestamp without time zone NOT NULL,
	updated timestamp without time zone,
	title varchar(100),
	role varchar(50) NOT NULL,
	description TEXT,
	company varchar(100),
	start_date timestamp without time zone NOT NULL,
	end_date timestamp without time zone
);

CREATE TABLE public.user (
	id bigint NOT NULL CONSTRAINT user_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created timestamp without time zone NOT NULL,
	updated timestamp without time zone,
	name varchar(100) NOT NULL,
	email varchar(255),
	enabled boolean NOT NULL DEFAULT TRUE,
	password text NOT NULL
);

INSERT INTO public.personal_info (id, created, title, first_name) VALUES ((select nextval('public.personal_info_id_seq')), now(), 'Example Title', 'Example name');
